---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-challenge
  labels:
    name: devops-challenge
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    name: cicd
